### ISSUE TITLE
Good tool, but not precise enough

### ISSUE THREAD

**Issue by mickaelmonsieur** [adolfintel/speedtest#12] opened 2017-01-11 09:37 UTC
Hello,
My little report... ;)
The calculated ping seems too high. (33 with Ookla, 49 with this one)
The upload seems underestimated. (3.36Mpbs with Ookla, 1.61Mbps with this one)
Only the download seems correct (28.18Mbps with Ookla, 26.35Mbps with this one)
I administer a local speedtest server for ookla, and I put this tool on a different server but the same network (same switch)
The tests were performed at 30 seconds intervals on a VDSL or I was the only user at that time and without wifi.

**Comment by adolfintel** [comment] 2017-01-11 10:57
If you tested this on my site, these results are normal because it's on a cheap hosting

**Comment by adolfintel** [comment] 2017-01-11 11:00
I'll leave the issue open for now and see if I can figure out why it gives me correct results.

**Comment by TheHolm** [comment] 2017-01-11 22:34
I'm getting similar experience.  Speedtest underestimate bandwidth by about factor of 2 for download. I'm confident that it is related only to test itself. I have control to all devices along the path. And ipref3 test between same two servers gives expected speeds 24Mbit down / 4Mbit up. But speedtest reports only 12-14 down and 3 up.  Web server is not busy and I use 10Mb random file as sample. I can collect some stats if required.

**Comment by adolfintel** [comment] 2017-01-12 06:18
Could it be HTTP overhead?

**Comment by TheHolm** [comment] 2017-01-12 10:31
Not for 50%. Test file is 10Mb, HTTP headers is about 1K max.  I guess problem is that it downloads data in one flow. So it makes it over sensitive to single packet drops.  Increasing test length make it way more accurate, as it gives tcp more time to adapt to link bandwith.

**Comment by jdc20181** [comment] 2017-02-04 16:33
Its because of latency with the server the results won't be the same every single time. 

Using WIFI Can have a huge impact on your Speed.. 

I don't use PHP in my speedtest project and here is this project results vs. my project results:

@adolfintel  Test: 7.77 MBPS

My Test (Project) : 7.79

Not kidding. 

This was with about 4 or 5 tabs open. 

I use a image for my speedtest project, on another respo creating a better results screen after retesting it usually gives me the accurate results. I have yet to figure out why it does that. 


 My speed should be around 15-18 MBPS (I  have 24mbps internet but with wifi its reduced)

P.S https://jdc20181.github.io/SpeedTest is where my project is :)

**Comment by adolfintel** [comment] 2017-02-04 18:35
@jdc20181 your test gives me an incorrect result too (7.35 mbit), but mine works fine here (15 mbit).

**Comment by jdc20181** [comment] 2017-02-04 18:39
Yea it happens. If you retest it will go more accurate most of that has to do with githubs servers. 

Test 2

http://screenshot.sh/mFcomkyaZLTdv

After refreshing I get the same result over and over, it is something idk how to fix, but it is mostly accurate. 

I can't get access to your site, it says Err_Connection_Timed_Out not sure if you got site problems or what is going on.

**Comment by adolfintel** [comment] 2017-02-04 18:41
I recently transfered the domain, so the DNS may not have propagated yet.
New link is speedtest.fdossena.com

**Comment by jdc20181** [comment] 2017-02-04 18:42
When I first started my project (just going into a general discussion) - I kept the cache that the browser automatically keeps - By not keeping cache it increased to a better result. 

It is not entirely true it isn't accurate or accurate either way - because none is accurate 100% even those who are well developed and way over my head lol

**Comment by adolfintel** [comment] 2017-02-04 18:44
Yes there is some weird stuff going on in all browser's XHR implementation. One weird thing I noticed is that some browser actually have it tied to the framerate, even when using web workers. Pure madness.

**Comment by jdc20181** [comment] 2017-02-04 18:46
Yea it depends on your DNS provider how fast it will be ready. 

Some take significantly longer some take shorter time.

**Comment by adolfintel** [comment] 2017-02-04 18:48
No, it doesn't depend on my provider's DNS, those are updated instantly, but all other DNS servers may have a cache that lasts for days, including the one you're using I guess. Plus the OS keeps its own cache too.

**Comment by jdc20181** [comment] 2017-02-04 18:49
hmm...Some take 24 hours to register though. Thats what I was saying.  

Could be, I will keep trying it worked for me once earlier to do the test I mentioned above - after that I got nothing

**Comment by ke-mccormick** [comment] 2017-02-26 08:34
What are the results supposed to be? Instantaneous? Simple moving average? Average?

I am not sure how the other speed tests show their results. I can see showing instantaneous or simple moving average, then at end the average.

**Comment by adolfintel** [comment] 2017-02-26 09:31
Each speedtest has its own algorithm. 
Mine takes samples of instant speed, assigns a weight depending on whether it's lower or higher than the current average, then uses the sample in a harmonic average. Samples are taken by using the onprogress callback function of XHR2.

**Comment by jdc20181** [comment] 2017-02-26 13:38
I made code adjustments and it seems to be matching other speed tests.

**Comment by adolfintel** [comment] 2017-02-26 14:54
Can you send a pull request please?

**Comment by jdc20181** [comment] 2017-02-26 15:08
no I meant on mine xD I don't understand PHP enough lol I am still learning.

**Comment by jdc20181** [comment] 2017-02-26 15:14
Alright here is what I did (with my experiment in my test) I think this does the same as in mine so I will give it ago. 

This varible ' dlStatus=((speed*8)/1048576.0).toFixed(2);' wasn't enough to get a accurate result. At least with mine. I changed this varible to 12 - Like so (mine is different from yours XD )

        'var bitsLoaded = downloadSize * 12 ; /* Experment: Change Var from 8 to 12 */'
And I seen a significant increase in accuracy. 


Maybe adjust the varible and it could be more precise. Also, you should use Bytes not MB's when measuring (idk how your code works its actually kinda hard to read lol) - Using Bytes is generally more accurate its a easier conversion.

**Comment by adolfintel** [comment] 2017-02-26 16:24
Yes I know my speedtest is kinda hard to read. It definitely needs a code overhaul.
Your test works quite differently though, and I'm sure your approach has issues with fast connections, buffering, and probably caching too.
See, at the moment there really are no accurate speed tests for HTML5, unless you're willing to use WebRTC maybe, but then it would get a loooot more complicated.

**Comment by jdc20181** [comment] 2017-02-26 16:30
I don't keep cache I use Meta Tags in the head to prevent cache

**Comment by adolfintel** [comment] 2017-02-26 16:33
Some browsers ignore it when you're loading via XHR ;) But it's not your case. I did not see this part:
```
var cacheBuster = "?nnn=" + startTime;
download.src = imageAddr + cacheBuster;
```

**Comment by jdc20181** [comment] 2017-02-26 16:34
:) yep.

**Comment by jdc20181** [comment] 2017-02-26 22:15
I haven't had a friend who has 1gbps internet try it again since the changes I put to make it run better, but yes it was significantly different but it could have been with wifi too you can lose up to 50% bandwidth (depending on your router etc) when using wifi vs a hardwire.

**Comment by ke-mccormick** [comment] 2017-02-27 00:10
PPPoE and WiFi will have lower MTUs, but the difference in reported speeds should not be more than 14%. Packet headers should also never be more than 5%. We are measuring throughput, not line speed.

**Comment by adolfintel** [comment] 2017-02-27 06:23
You have to consider 2 other things:
-Interference
-Your machine may not be fast enough to handle all that data
-The fact that XHR events seem to be somehow tied to the framerate of the window

**Comment by ke-mccormick** [comment] 2017-02-27 18:41
I noticed the speed being measured on our server was more than 100 Mbps, but my client is on 100 Mbps connection. You should expect this measured speed to be around 95 Mbps or less due to overhead. So I looked at the code and found you are multiplying the speed by 1.25. That means measurements are 25% larger than they should be. I removed that multiplier and now speeds are closer to what I would expect.

Old
`var instspd=event.loaded<=0?speed:((event.loaded-prevLoaded)/((new Date().getTime()-prevT)/1000.0))*1.25;`

New
`var instspd=event.loaded<=0?speed:((event.loaded-prevLoaded)/((new Date().getTime()-prevT)/1000.0));`

**Comment by adolfintel** [comment] 2017-02-27 18:43
Yes, there is 1.25 multiplier because I noticed a ~25% difference between the speed reported by my network card and the one I got from the speedtest. Am I the only one who had this?

**Comment by ke-mccormick** [comment] 2017-02-27 19:45
Right now I am getting 21%, but earlier was about 8%. Hard to determine with our server since the server is busy right now.

**Comment by jdc20181** [comment] 2017-02-27 20:20
How do you measure the amount of data as it is being processed, do you use bytes or mb? You should be using bytes because of how the conversion between them all are. 

Try adjusting this, and btw, I use Github to host my project the difference is you can't use php on gh pages.

**Comment by ke-mccormick** [comment] 2017-02-27 20:23
Everything is done in bytes until reporting the speed, then the value is multiplied by 8 to give bits.

**Comment by jdc20181** [comment] 2017-02-27 20:33
alright why not adjust that varible? Go try mine, I recently adjusted the"8" varible to a larger number. It actually gives almost the same thing (about 1/2 to 2 mbps off) as other projects like speedof.me etc. 

Actually if you do a google search speedof.me was originally a open source project. Now its a FOR profit project. The open source version was very buggy and wasn't exactly the best coded. 

I will see if I can find the respo. and give a link may find something useful.  ( i think it was speedof me)

Anyways I will see what I can find. I have made improvements with my code (on my project) which I started last year xD I mainly am collaborating to learn. I am not familar with php and as I mentioned his js code is kinda cluttered. 

Plus we both want very useful tools. 

Alright [here ](https://github.com/sergiogcx/html5_speedtest) it is - If you click on teh link it takes you to the speedof.me website. 

Maybe someone can get some inspiration from it? its the closest thing to this (i don't think it uses php though. )

**Comment by ke-mccormick** [comment] 2017-02-27 21:43
speedof.me shows my max download higher than 100mbps. With overhead this can not be more than ~95.5 mbps. The resulting speed was 98.72 mbps which is impossible. They are falsely reporting the throughput to a higher number. Adjusting the 8 variable to a bigger number just means you changed the definition of Byte to be more than 8 bits.

**Comment by jdc20181** [comment] 2017-02-27 22:14
That is interesting....

I changed it on my project and it improved the results  - might not have been the best but that was about the only thing I could change to make it work better. 


Anyways so whatelse can one do to improve accuracy, please note mine is completely different than this one.

I doubt there will be one that will be 100% truly accurate. I mean seriously.

**Comment by ke-mccormick** [comment] 2017-02-27 22:37
Accuracy is 100% but the values are only in the moment. You have to deal with congestion, server load, and many other variable. I am going to submit some changes and see what jdc20181. I change the calculation method to a Cumulative Moving Average.

Here is a link to the page.

http://www.wiu.edu/users/mukem1/speedtest/

**Comment by jdc20181** [comment] 2017-02-28 00:14
That link ^ is way off 

http://screenshot.sh/n9KeRdAEuyux5

My actual speed should be in the 20's. (max is 24mbps)

**Comment by jdc20181** [comment] 2017-02-28 00:15
oh and i know that your server plays a big role, its location (causing high latency will be not be good!)

speed of the server. and many  other factors as well as teh ones you said

**Comment by adolfintel** [comment] 2017-02-28 05:39
Sorry for the late answer. ke-mccormick's test may be ok but the server that it's hosted on is too slow to be sure.
I think I need to explain why there were those *1.25 multipliers on the speed:
XHR as you know works through HTTP. HTTP as you know has chunking, and it runs on top of TCP, IP, ethernet, and they all have their own headers. When I ran the test on my site, I saw it report ~13-14mbps on my 18-20mbps connection; I looked at the speed reported by the network card and there was a ~20-25% difference, reporting ~18mbps, so I thought that the difference was caused by headers and chunking (if you look at garbage.php you'll see that it sends 1mb chunks).
Now that I know it is wrong, I'm reconsidering this multiplier, either removing it entirely or lowering it to maybe 1.1
Changing the 8 to something else has the same effect but it would be an incorrect conversion from bytes to bits per second.
What do you think?

**Comment by jdc20181** [comment] 2017-02-28 13:33
You can always make an a experimental version... thats what I do sometimes, and it can always be changed back if need be xD

**Comment by dennore** [comment] 2017-02-28 21:18
i think the 1.25 should be taken out here, and instead add a multiple stream download/upload to get better results.
for example ookla (speedtest.net) is doing around 10-12 sessions within a single speedtest to get precise results

**Comment by adolfintel** [comment] 2017-03-01 06:08
Hmmm sounds like an idea. I'll give it a try in the next few hours and see if it works better

**Comment by adolfintel** [comment] 2017-03-01 07:11
Looks like you had a good idea, they're not that far off.
Can you try it in your browser? http://testing.fdossena.com/example4.html

![2017-03-01 08_10_38-speedtest - chromium](https://cloud.githubusercontent.com/assets/16307689/23449395/9a8ecc72-fe56-11e6-8803-7bfc15297b09.png)

**Comment by dennore** [comment] 2017-03-01 09:58
wow, that was a fast change... yes my 1Gbit link gets maxed out better now, for download. but the upload seems broken for me now... im testing on chrome. wanna see a video of my speedtest including the networkpane in the taskmanager?

**Comment by adolfintel** [comment] 2017-03-01 10:32
Broken how exactly?

**Comment by TheHolm** [comment] 2017-03-01 10:40
I'm getting 0 upload speed with Chrome too.

**Comment by adolfintel** [comment] 2017-03-01 10:43
What the fuck?
I use Chrome and it works.
I should mention that I moved the Upload test after the ping test, which seemed to give better results

**Comment by dennore** [comment] 2017-03-01 11:48
it just stops uploading after ~20 MB data sent.

i just figured out why...
(ur junksize is 1MB and you loop it 	for(var i=0;i<20;i++) req.push(r);
should it loop until the timer stops? time_ul:15

.. i have increased the var r=new ArrayBuffer(20485760); to 20 MB chunks
how it works perfect on Edge12 with 3 streams upload and download. maxing out my 1G Line.
i've also changed the dlStatus=((speed*8)/925000.0).toFixed(2); to mach the TCP and HTTP overhead, thats being produced, now it works like a charm on edge

**Comment by chmutoff** [comment] 2017-03-01 12:17
Hello!

Will you make a commit of this changes? I am very, very interested in this speedtest. As you mentioned above i can't push more than 400 - 500 Mbps in my local network having 1Gbps equipment and a powerful server to run the speedtest.

Regards, Anton.

**Comment by adolfintel** [comment] 2017-03-01 15:19
@chmutoff I will push the changes as soon as I fix the bug mentioned by @dennore. So expect a commit in a few hours and by tomorrow I will also release a new version with comments and documentation, since the project is evolving from the little thing that it used to be

**Comment by dennore** [comment] 2017-03-01 15:59
great work :+1:

**Comment by adolfintel** [comment] 2017-03-01 16:26
I have uploaded a new experimental branch with the modifications.
You can test it here (clean your cache first, just to be sure): http://testing.fdossena.com/example4.html

@dennore let me know if the download still reports the wrong speed

**Comment by ke-mccormick** [comment] 2017-03-01 16:47
http://testing.fdossena.com/example4.html is not loading for me.

**Comment by adolfintel** [comment] 2017-03-01 16:48
I can open it just fine. Try again, maybe clear your browser cache

**Comment by ke-mccormick** [comment] 2017-03-01 16:50
This site can’t be reached

**Comment by adolfintel** [comment] 2017-03-01 16:57
Shit. Well, that's a problem with my site. Can you test the speedtest locally?

**Comment by jdc20181** [comment] 2017-03-01 16:57
I got through fine about 5 min ago

**Comment by dennore** [comment] 2017-03-01 17:08
i just did some more testing on my gig link. and figured out that the garbage.php size on 100MB chunks is impacting the brower performance and makes chrome crash somehow... e.g. 5 streams each 100MB will loaded into memory of chrome, which will make it crash...

but decreasing the chunksize to .e.g. 5MB will create spikes in the transfer, because the file will be redownloaded multiple times. (some small breaks in between)

i have tried different settings, but none of them will make it work, like it should

i will continue testing tomorrow.

regards

**Comment by dennore** [comment] 2017-03-01 17:13
same here. cant load http://testing.fdossena.com/example4.html

**Comment by adolfintel** [comment] 2017-03-01 17:20
Yes of course, it makes it allocate a bunch of memory, because we have 10 streams. I have to find some way around that. Maybe 20mb chunks and more streams?

**Comment by dennore** [comment] 2017-03-01 17:21
testing your branch (experimental) on my server:
chrome: http://imgur.com/a/Dg8E4
edge: http://imgur.com/a/sl9eg

**Comment by adolfintel** [comment] 2017-03-01 17:22
I think Chrome is doing that because it's wasting time allocating memory. I have to find a way around it

**Comment by dennore** [comment] 2017-03-01 17:27
another thing here: with 5 MB chunksize in the garbage.php 

http://imgur.com/a/RtTBb

**Comment by adolfintel** [comment] 2017-03-01 17:28
20mb chunks seems to be good from here. Can you confirm?

**Comment by dennore** [comment] 2017-03-01 17:33
added images to http://imgur.com/a/RtTBb for 20 mb chunks

**Comment by adolfintel** [comment] 2017-03-01 17:35
Maybe 3-4 streams with 100mb chunks?

**Comment by adolfintel** [comment] 2017-03-01 17:38
Ooooh look at this, it could prevent it from raping memory
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by dennore** [comment] 2017-03-01 18:05
worth giving it a try...

could you add a example.html to the fork where you can set the streams for up and download separately and the chunksize in the html... like a dropdownbox or simple textfiles... would be easier for testing purposes

**Comment by adolfintel** [comment] 2017-03-01 18:10
Nah that fetch api is still shit, you can't abort requests yet.
I'll have to find another solution

**Comment by jdc20181** [comment] 2017-03-01 18:17
You should time the results. Or time the download of the data. Or simply
upgrade your hosting...sounds like it sucks

**Comment by adolfintel** [comment] 2017-03-01 18:24
Well for 20 bucks a year you can't expect it to handle gigabit connections. It's good enough to host my projects though

**Comment by jdc20181** [comment] 2017-03-01 18:26
Can you PM what the host is called I wanna get a portfolio started soon...

**Comment by adolfintel** [comment] 2017-03-01 18:31
The hosting is Netsons Italy

**Comment by adolfintel** [comment] 2017-03-01 18:34
I just uploaded a new version with Fetch API implemented for Chrome 43+and 100mb chunks, let me know if it's any better

**Comment by jdc20181** [comment] 2017-03-01 18:35
:( lol I can't speak italian.  What is the conversion from European money  to USD? 

I was thinking about buying a VPS unmanaged for about $30 a year I think it was gonna be...

**Comment by jdc20181** [comment] 2017-03-01 18:35
I need to buy some hosting and stop relying on Github so much lol

**Comment by adolfintel** [comment] 2017-03-01 18:36
They offer VPS starting from 12.20€/month (~15USD) with 1 core, 1gb of ram, 50gb ssd, 100mbit network

**Comment by adolfintel** [comment] 2017-03-01 18:37
I bet my site has alredy been throttled today with all the traffic from this test hahah

**Comment by jdc20181** [comment] 2017-03-01 18:37
Cool if I could speak Italian or get it to convert right lol it would cool

**Comment by jdc20181** [comment] 2017-03-01 18:53
Lol- you better upgrade...

**Comment by adolfintel** [comment] 2017-03-01 19:03
Looks like Fetch API is even worse, leaks memory like no tomorrow

**Comment by dennore** [comment] 2017-03-01 19:23
well. i didn't used any traffic from your site. i was always testing your code on my local server

**Comment by adolfintel** [comment] 2017-03-01 19:27
I wasn't accusing you, I am the one who's using up all the bandwidth.
Anyways, I think this quirk is the best solution, at least for the moment:
-10mb chunks with 10 streams for chrom*
-20mb chunks with 10 streams for other browsers

I'm also trying to investigate possible causes for memory leak in XHR, then I'll commit the new experimental version

**Comment by jdc20181** [comment] 2017-03-01 19:28
It seems to be a well known issue with the memory leak thing, I will help you do some research but everything will be informational. Idk anything about this kinda thing lol, I barely knew how to make my project because I am learning xD

**Comment by jdc20181** [comment] 2017-03-01 19:29
General Information Questions:

How many HTTP Requests are being requested? 

(will edit wait for more)

**Comment by adolfintel** [comment] 2017-03-01 19:31
At the moment, 10 parallel XHR. I see the tab using ~400mb of ram after a few minutes of continuous running, but I also see it slowly increasing, so there might be some leaking

**Comment by jdc20181** [comment] 2017-03-01 19:31
I assume you already have this (considering you actually told me.) but you may look through this and see if there is something you are missing? If you cleaned your code where I can read it I may be able to help more xD

**Comment by jdc20181** [comment] 2017-03-01 19:32
Oops forgot the link 
sorry here ya are

http://javascript.info/tutorial/memory-leaks

**Comment by adolfintel** [comment] 2017-03-01 19:35
If you look at the experimental branch you'll see I have cleaned it up quite a little bit, but this project is getting a lot more complicated than I imagined. I hope I can do something to make it better

**Comment by jdc20181** [comment] 2017-03-01 19:36
http://pastebin.com/KvXEgJkn (its from [this](http://stackoverflow.com/questions/29062552/memory-leak-with-xmlhttprequest) issue)

**Comment by jdc20181** [comment] 2017-03-01 19:39
Why not prevent cache in another way? 


Also I may have to read the TOS of your webhost as it may be blocking something -  creating the memory leak..

**Comment by adolfintel** [comment] 2017-03-01 19:42
Let me explain why I think there might be a memory leak in the download test:
We have a function that creates an XHR request; in the onload event for this request, it calls the function that creates the XHR request again.
Now... in theory, since XHR is asynchronous, when the second XHR is created, the function ends and the first one is deallocated by the garbage collector when it's called. However, some reference to the first XHR may be passed on to the second by some obscure JS sorcery. So I did the cheapest thing I possibly could, and made that function create a 1ms timer that creates the second XHR, thus detaching the two XHRs completely.
And now I see that the memory usage is stable, fluctuating between 300 and 500 mb when the GC is called.

**Comment by jdc20181** [comment] 2017-03-01 19:44
interesting..

**Comment by dennore** [comment] 2017-03-01 19:49
i just downloaded your code 20mins ago and put it on my server... now the download is broken. its not downloading anything

**Comment by adolfintel** [comment] 2017-03-01 19:54
Wait, I'm making changes ;)

**Comment by adolfintel** [comment] 2017-03-01 19:56
@dennore try it now

**Comment by adolfintel** [comment] 2017-03-01 20:00
@jdc20181 I have been running the test for 10 minutes with the profiler attached and there seem to be no memory leaks in the version I just uploaded.
However, the CPU overhead from all the XHR events and the GC may be what cause @dennore to get low speeds in chrome. I mean, I have a 20 mbit connection and uses 8-10% of the CPU, I guess a gigabit connection will saturate it?

**Comment by dennore** [comment] 2017-03-01 20:34
yes i realized my cpu runs on 100% while download and 50% while upload...
ill add more cpus on my test vm tomorrow... to see if thats the bottleneck here

**Comment by jdc20181** [comment] 2017-03-01 22:58
Best way to do it is add a handler and tell the person your connection is
too big for this test ( something like that) but idk how you would execute
it.

**Comment by adolfintel** [comment] 2017-03-02 05:55
I don't think adding more cores will do anything, I doubt XHR is multithread

**Comment by adolfintel** [comment] 2017-03-02 06:02
@jdc20181 only Chrome Dev has the chrome.process object, so that's out of the question unfortunately :(

**Comment by adolfintel** [comment] 2017-03-02 06:19
@dennore Can you try downloading a file off mega with that gigabit connection? Do you get high cpu usage there too?

**Comment by dennore** [comment] 2017-03-02 07:13
no, not on a regular download...

**Comment by adolfintel** [comment] 2017-03-02 07:20
Strange, on my machine I have relatively high CPU usage and lots of memory being used

**Comment by adolfintel** [comment] 2017-03-02 07:30
I googled around a bit and found that I'm not the first one to notice high CPU usage with XHR. It looks like it was improved in Firefox, but Chrome still has it. Surprisingly, Edge is the best here. There seems to be no solution, at least until the Fetch API is improved (at the moment, it's even worse than XHR, I implemented it but it's disabled by default).

So, here's what I'll do:
-I'll write some doc, update the examples, etc. and commit the new version on the master branch
-In the doc I'll mention this as a known issue
-I'll close all issues and open a new one called "Problems with Gigabit connections"
-We all keep an eye out for progress in the development of Fetch API streaming

Anyway, I want to thank all of you for helping me out with this project. Despite this issue with gigabit connections, this test has improved a lot and is now really good.

**Comment by dennore** [comment] 2017-03-02 08:22
will it change anything if you set the xhr.responsetype?

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType

**Comment by adolfintel** [comment] 2017-03-02 08:26
Hmmm, it's worth a try I guess

**Comment by adolfintel** [comment] 2017-03-02 08:32
Update: I tried responseType='blob' and see no significant difference in CPU usage. Memory usage is lower though so I guess I'll keep it.
I'lll commit the changes in a moment

**Comment by dennore** [comment] 2017-03-02 08:54
what about arraybuffer?

**Comment by adolfintel** [comment] 2017-03-02 08:56
Same memory usage as without responseType. Blob seems to be better

**Comment by dennore** [comment] 2017-03-02 09:00
i increased my core count on this vm from 4 to 12. now my cpu does not get to 100% anymore.. its just around 20%, and yes chrome uses multithread :+1: 

i just did some tests with the cktest.html
here are screenshots all on chrome, notice that sometimes i get wrong results in downloadspeed vs. real speed (from task manager)
and sometimes, the download wont stop, it willl continue to download something while pingtest and uploading

just see yourself here:
http://imgur.com/a/kDhff

**Comment by adolfintel** [comment] 2017-03-02 09:05
Interesting. So a single large chunk is better for Chrome apparently. I guess I'll do 1 chunk of 500mb just to avoid using too much memory.
Also interesting when it didn't stop the download test, I wonder what caused it...

**Comment by dennore** [comment] 2017-03-02 09:12
if i have a large chunk, the memory gets loaded full.. if i have many small chunks, memory are fine, but the link will not get to 100%, maybe the chunks in multistream should not be all at same size (on the start) so that hey wont all stop at the same time, if you know what i mean: here a image to clarify:
http://imgur.com/a/Emcsc

**Comment by adolfintel** [comment] 2017-03-02 09:16
Yes I understand. Makes sense. I could also delay them slightly.
Can you do a test first? 500mb chunks with 2 streams?

**Comment by dennore** [comment] 2017-03-02 09:23
sure, here you are:
http://imgur.com/a/Dy4g0

**Comment by adolfintel** [comment] 2017-03-02 09:26
Thank you. I guess I'll stick with that for the moment until we find a better solution
I'll also add some code to make absolutely sure that download XHRs are not active after the download test is over.
And finally, I'll try delaying XHR request creations so they don't end in sync. (I doubt it happens but who knows)

**Comment by dennore** [comment] 2017-03-02 09:29
but a multistream is really nessessary on a speedtest, for multiple reasons:
- a regular firewall cannot handle 1 G/s in a single stream, e.g. our firewall is maxed at 750MBits/per stream depending on the load. for now i only get 350MBits (my tests on screenshots are without a firewall in between)
- multiple streams will increase the troughput on a higher-latency network [WAN] (due to the fact of troughput is depended on paketsize vs. ping), as i mentioned realier (my tests are on a <1ms latency network)

**Comment by adolfintel** [comment] 2017-03-02 09:30
Let me implement the delay thing, then we'll see if it gives better results ;) It should take less than an hour

**Comment by dennore** [comment] 2017-03-02 09:38
checkout these screenshots (chrome) with a firewall in between (sorry for windows7) :)

http://imgur.com/a/B1Noj

**Comment by adolfintel** [comment] 2017-03-02 09:44
I've implemented delayed XHR requests, give it a try

**Comment by dennore** [comment] 2017-03-02 10:16
wow it works like a charm on my chrome now... just a little spiky at the end.
did you changed more? cause the download speed is accurate now.

http://imgur.com/a/T1WaM

**Comment by adolfintel** [comment] 2017-03-02 10:17
Fuck yea!

**Comment by adolfintel** [comment] 2017-03-02 10:17
Good lord that took a while to figure out.

**Comment by dennore** [comment] 2017-03-02 10:19
just another test here : awesome:!!!!!

http://imgur.com/a/Ua6Gu

i notice that it writes on my disk (c:) on download... is that cause of the XHR.responsetype?

**Comment by adolfintel** [comment] 2017-03-02 10:20
It could be. I guess it writes blobs to disk to avoid using too much memory

**Comment by dennore** [comment] 2017-03-02 10:24
THATS fucking amazing... it now even runs on my windows7 behind the firewall with full troughput and correct speed display in chrome. ur, so great! (chunk 20 steam 5)

**Comment by adolfintel** [comment] 2017-03-02 10:25
Holy fuck who would have thought that delaying them by 100ms would make such a huge difference.

**Comment by dennore** [comment] 2017-03-02 10:28
is there any reason why not doing the ping-test at the start, before (download) the line is utilized?
because i think its affecting my ping, to short delays after download is finished.

**Comment by adolfintel** [comment] 2017-03-02 10:30
Yes, I could move it at the beginning.
I have to go to university now, but I'll definitely make some tests and release on the master branch in a few hours

**Comment by dennore** [comment] 2017-03-02 10:34
on your latest commit firefox won't download anything for me... upload works...
edge is great, same as chrome.

**Comment by dennore** [comment] 2017-03-02 10:38
never mind, just on my computer, on the vm with the latest firefox version it works!

**Comment by adolfintel** [comment] 2017-03-02 10:38
Firefox works for me as well.
Safari is a bit low, but then again safari is shite so who cares

**Comment by dennore** [comment] 2017-03-02 10:54
yes i just noticed as well on my vm (mac os) on safari its not that fast... download is ok , upload will slow down after some seconds... and cpu util is very high... (shitty safari)
chrome on mac runs perfectly...

even on my iphone its now working without a crash, with chunk20/streams 5/5.
mobile safarie on iphone 7 (ios 10) http://imgur.com/DvCw8mG

**Comment by dennore** [comment] 2017-03-02 11:00
best results on my mobile safari with chunk5, stream10(both) 328/216 Mbits

**Comment by adolfintel** [comment] 2017-03-02 11:01
Thank you :)

**Comment by dennore** [comment] 2017-03-02 12:12
you might want to consider using "arraybuffer" instead of "blob" for download. (maybe for upload too, but i guess its not needed)

i just tested it and if you use blob, it writes the file to disk (in html5 filesystem on the client)
if you use arraybuffer you can decide what to do with the result, before writing it to disk, or even dont write it at all...

conclusion: with arraybuffer my disk is not getting under heavy load, which can be a bottleneck if you use even faster connections like 10Gbit

speedtests running also fine for me if i use arraybuffer

**Comment by adolfintel** [comment] 2017-03-02 12:13
Well, let's add the setting then 👍

**Comment by dennore** [comment] 2017-03-02 12:28
hm... arraybuffer seems to fillup the ram again. but maybe there is a way to cleanup the 20mb chunk after its downloaded...

**Comment by adolfintel** [comment] 2017-03-02 12:29
That's why I was using blob.
The only way to unload stuff in JS is wait for GC to be called. So, do you think we should have blob or arraybuffer as default value?

**Comment by dennore** [comment] 2017-03-02 13:35
i think arraybuffer if you are able do cleanup the buffers after each chunk.. did you read this? 
http://stackoverflow.com/questions/21554346/xmlhttprequest-freeing-after-use

**Comment by adolfintel** [comment] 2017-03-02 13:39
Yes, it says pretty much what I just said. There is no explicit way to call the GC in JS: it is called automatically when memory is needed and deallocates objects that are no longer referenced, which would be alright if it didn't take several milliseconds (after all, we create dozens of huge objects).
I think we should keep blob as default, since I see it works fine on mobile too. What do you think?

**Comment by dennore** [comment] 2017-03-02 14:25
are you reusing your xhr[i] for each finished chunk or are you creating a new ones leaving the old in memory?

read this: http://nullprogram.com/blog/2013/02/08/

**Comment by adolfintel** [comment] 2017-03-02 14:26
I create old ones. Calling open and send again on an existing XHR does not work in all browsers

**Comment by dennore** [comment] 2017-03-02 14:28
have you tried deleting the old instead of setting it to null?

**Comment by adolfintel** [comment] 2017-03-02 14:29
Hmm good idea. Let's see if it makes any difference

**Comment by adolfintel** [comment] 2017-03-02 14:36
Check the new commit and see if there's any difference

**Comment by dennore** [comment] 2017-03-02 14:39
where is the cktest.html :(

**Comment by dennore** [comment] 2017-03-02 14:44
nope no difference... chrome randomy drops the ram it seems.... (during download)
see: http://imgur.com/a/ybuRJ

**Comment by adolfintel** [comment] 2017-03-02 14:45
Yes this commit deletes instead of setting to null.

I deleted cktest from this commit, I'll put it back in the next commit (experimental only)

On March 2, 2017 3:39:43 PM GMT+01:00, dennore <notifications@github.com> wrote:
>where is the cktest.html :(
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/12#issuecomment-283670568

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adolfintel** [comment] 2017-03-02 14:46
Ok, we'll do this but go back to using null then, just in case

On March 2, 2017 3:44:48 PM GMT+01:00, dennore <notifications@github.com> wrote:
>nope no difference... chrome randomy drops the ram it seems.... (during
>download)
>see: http://imgur.com/a/ybuRJ
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/12#issuecomment-283672008

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dennore** [comment] 2017-03-02 14:51
here 2 more tests without restarting chrome

http://imgur.com/a/HnQWh

**Comment by dennore** [comment] 2017-03-02 14:56
oh wait up ... you implemented blob / arraybuffer as variable now... i just tested with the old cktest.html

**Comment by dennore** [comment] 2017-03-02 14:58
on example4.html it cleansup ram after download is finished. (what it didnt do before...)

**Comment by dennore** [comment] 2017-03-02 15:12
hm useblob is set to false
	xhr_dlUseBlob:false, //if set to true, it reduces ram usage but uses the hard drive (useful with large garbagePhp_chunkSize and/or high xhr_dlMultistream)


and it still uses my disk to write on...

**Comment by adolfintel** [comment] 2017-03-02 16:06
Arraybuffer still writes on the disk?

**Comment by adolfintel** [comment] 2017-03-02 16:08
At like 188 try replacing with 
if(settings.xhr_dlUseBlob) xhr[i].responseType='blob';
and see if it still uses the disk. Because it doesn't do it here, but I have a regular 20mbit connection

**Comment by dennore** [comment] 2017-03-02 16:52
just for fun: speedtest running on a 10Gig network

http://imgur.com/a/vmF2d

**Comment by dennore** [comment] 2017-03-02 16:52
no arraybuffer is fine... it was my fault there

**Comment by adolfintel** [comment] 2017-03-02 16:54
Ok, so we'll go with default arraybuffer :)
Congratulations for that 10gbps network hahaha

**Comment by adolfintel** [comment] 2017-03-02 16:55
I'll commit everything to master soon and close all issues

**Comment by adolfintel** [comment] 2017-03-02 17:09
Issue closed with commit fce6a67be0b61dbbac1c448b329fdf54175ed721

**Closed by adolfintel** 2017-03-02 17:09 UTC

**Comment by dennore** [comment] 2017-03-02 20:43
hey bro,

sorry to ping you again, where can i find the cktest.html now?
did you forgot to change the order of the test? 
1. ping
2. dl
3. ul

best wishes
dennore

**Comment by adolfintel** [comment] 2017-03-02 20:56
I made a cktest branch, you can get it there.
And yes I did forget to change the order of tests, I guess I'll do it in the next release, no big deal.

**Comment by ke-mccormick** [comment] 2017-03-03 03:06
How did you dome up with 925000 instead of 1048576?

I was thinking, about other speed tests maybe dividing by decimal Mbits 1,000,000 rather than binary Mibits 1,048,576.

If you take in account 5% overhead for TCP/IP, 950,000 would be perfect.

**Comment by ke-mccormick** [comment] 2017-03-03 04:49
I know it is not your issue, but I think our Cisco IPS  has blocked your speed test.

Your new code was working on our server, I was accessing from home and suddenly stopped working.

Guess I am talking with out Net, Sec. guy tomorrow to figure out what is happening.

Keep you all posted in case someone else runs in to this issue.

**Comment by adolfintel** [comment] 2017-03-03 06:45
925000 was suggested by dennore, to compensate TCP, IP, and HTTP overhead (chunking). It looks right to me, but honestly I didn't to the math.

Your firewall probably blocked it because of the multistream, you can force xhr_dlMultistream and xhr_ulMultistream to 1. The test will be less accurate though so it's better if you fix the configuration on that firewall.

**Comment by dennore** [comment] 2017-03-03 08:06
hey all, yes i agree on your calculation with the 5% but somehow if i use this value, it's not matching with the real speed, and it's not possible to get more that 1gbit on a 1gbit connection... i will check out a wireshark trace later to see, if xhr's maybe produce more that 5% overhead.

**Comment by dennore** [comment] 2017-03-03 08:11
i also just read something that there is a maximum of parallel xhr's per domainname depending on the browser. on chrome i tested more than 5 are not working... and somehow for upload only 4

**Comment by adolfintel** [comment] 2017-03-03 08:44
Here I see about 10 download streams, then it delays them. Maybe it depends on the type of connection that it detects.
Anyway, it's fine, even if it delays some connections, it does not affect the accuracy of the test.

**Comment by dennore** [comment] 2017-03-03 12:37
hey again, i just told a collegue of mine, who is a htmldev to check about the memoryleak thing.. and he found a solution. he is going to send you the update via github. and yes maybe the 950000 would be more apropriate... regards

**Comment by adolfintel** [comment] 2017-03-03 12:38
Oh, good, looking forward to it

**Comment by dennore** [comment] 2017-03-03 15:11
just see, that edge is not cleaning up ram on .abort()
only works on chrome..

maybe you can reuse existing xhrs instead of creating new once...
see here: http://nullprogram.com/blog/2013/02/08/

> To work around this, the Closure Library pools XHRs. Disciplined re-use of XHR objects can free the developer from relying on the browser to dispose of old XHR objects. Browsers limit the number of simultaneous HTTP requests to somewhere between 2 and 5, so XHR pools should typically stay very small.

**Comment by adolfintel** [comment] 2017-03-03 15:48
Yes I noticed, I guess chrome's implementation is different.
Still, I put a try-catch around that abort, since I doubt aborting a request after it's done is standard.

As for reusing XHRs: that does not work in all browsers (I think firefox did not like it but I'm not sure). Still, the memory usage is reasonable and only lasts for a few seconds, I don't think we should put more effort into it for now.

**Comment by dennore** [comment] 2017-03-03 16:11
true maybe its not designed for 10 gb connections... cause my ram is loading full very fast on 10gbit :)

**Comment by adolfintel** [comment] 2017-03-03 16:12
Not yet at least ;)
Maybe the Fetch API will improve in the future and it will be able to handle 10gbps just fine. At the moment, it's crap so we'll stick with XHR.

**Comment by dennore** [comment] 2017-03-03 16:15
http://imgur.com/a/aJBsy

**Comment by dennore** [comment] 2017-03-03 16:18
http://imgur.com/a/aJBsy (updated) check out both edge and chrome.
you still forgot to order ping before download test bro !

**Comment by adolfintel** [comment] 2017-03-03 16:20
Heh, that's not too bad, I was expecting worse.
Yes I know I didn't change the order yet. I'll do it. Eventually hahah

**Comment by jdc20181** [comment] 2017-03-03 16:57
You outta create a Gitter room for this project so we can collaborate..and
help you solve issues.
